context:
  version: "2.0.8"

package:
  name: berglas
  version: ${{ version }}

source:
  url: https://github.com/GoogleCloudPlatform/berglas/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1765994e212c0281b215aabae3ec95eef2894a6bfa99f5434db4bf6814c0c940

build:
  number: 0
  script:
    - if: unix
      then:
        - go build -ldflags="-s -w -X github.com/GoogleCloudPlatform/berglas/v2/internal/version.name=berglas -X github.com/GoogleCloudPlatform/berglas/v2/internal/version.version=${{ version }}" -o $PREFIX/bin/berglas
      else:
        - go build -ldflags="-s -w -X github.com/GoogleCloudPlatform/berglas/v2/internal/version.name=berglas -X github.com/GoogleCloudPlatform/berglas/v2/internal/version.version=${{ version }}" -o %PREFIX%/bin/berglas.exe
    - if: unix and target_platform == build_platform
      then:
        - mkdir -p $PREFIX/share/bash-completion/completions
        - $PREFIX/bin/berglas completion bash > $PREFIX/share/bash-completion/completions/berglas
        - mkdir -p $PREFIX/share/zsh/site-functions
        - $PREFIX/bin/berglas completion zsh > $PREFIX/share/zsh/site-functions/_berglas

    - go-licenses save --save_path ${{ "$SRC_DIR" if unix else "%SRC_DIR%" }}/license-files .

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - berglas --version

about:
  homepage: https://github.com/GoogleCloudPlatform/berglas
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Tool for managing secrets on Google Cloud

extra:
  recipe-maintainers:
    - wolfv
